bot_config:
  user_handle_logic: blacklist #模式。可填 blacklist, whitelist。blacklist下，屏蔽指定用户，whitelist下，只处理指定用户。
  user_handle_logic_operate_level: 1000 #拉黑、解黑用户所需操作权限
  group_handle_logic: blacklist #模式。可填 blacklist, whitelist。blacklist下，屏蔽指定群，whitelist下，只处理指定群。
  group_handle_logic_operate_level: 1000 #拉黑、解黑群所需操作权限
api_implements: #花里胡哨
   nudge:               #戳一戳设置。
     counter_probability: 100 #反击概率
     replylist:       #如果开启aiReplyCore，将不使用此处配置回复
       - "戳我干嘛呀！"
acg_information:
  bangumi_query_prefix: "/" #番剧查询类命令前缀
basic_plugin:
  setu:
    r18mode: true
    gray_layer: true #是否开启灰度图功能
  tarot:
    lock: false #是否开启卡片锁定功能
    mode: "blueArchive" #牌面。可填 blueArchive,bilibili,AbstractImages
JMComic:            #禁漫相关功能设置
  previewPages: 6  #验车预览页数
  autoClearPDF: True #下载后自动清除pdf
  savePath: "data/pictures/benzi"  #下载为pdf的默认保存路径
bili_dynamic:
  enable: true #是否开启动态推送功能
  dynamic_interval: 300 #动态推送间隔时间，单位为秒
  screen_shot_mode: "pc" #mobile为移动端截图，pc为PC端截图